name: lyrics_genius
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - matplotlib
  - wordcloud
  - spotipy
  - requests
  - jupyterlab
  - ipykernel  # Pour les notebooks Jupyter
  - kedro
  - kedro-viz
  - kedro-datasets
  - nltk
  - langdetect
  - transformers
  - pytorch
  - tensorflow
  - pip:
    - lyricsgenius
    - genius